image:
  name: docker/compose:1.27.4

services:
  - docker:dind

stages:
#  - build
  - deploy

before_script:
  - "which ssh-agent || (apk update && apk add openssh)"
  - apk add bash
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - chmod 644 ~/.ssh/known_hosts
  - docker login registry.gitlab.com -u $USERNAME -p $TOKEN

#build:
#  stage: build
#  script:
#    - docker-compose up --build -d
#    - docker push registry.gitlab.com/pote.dev/website:nextjs
#    - docker push registry.gitlab.com/pote.dev/website:nginx

deploy:
  stage: deploy
  script:
    - chmod +x ./deploy.sh
    - scp -r ./nginx/default.conf ./docker-compose.yml $SSH_USER@$SSH_SERVER:/home/potedev/app
    - ssh $SSH_USER@$SSH_SERVER && cd /home/potedev/app && docker login registry.gitlab.com -u $USERNAME -p $TOKEN && docker pull registry.gitlab.com/pote.dev/website:nextjs
#    - ssh $SSH_USER@$SSH_SERVER:/home/potedev/app && docker login registry.gitlab.com -u $USERNAME -p $TOKEN && docker pull registry.gitlab.com/pote.dev/website:nextjs