image:
  name: docker/compose

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

before_script:
  - "which ssh-agent || (apk update && apk add openssh)"
  - apk add bash
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - echo "$DOCKER_AUTH_CONFIG"
  - chmod 700 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - chmod 644 ~/.ssh/known_hosts
  - export IMAGE=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  - docker login registry.gitlab.com -u $USERNAME -p $TOKEN
  - bash ./scripts/setup_env.sh

build:
  stage: build
  script:
    - export NEXTJS_IMAGE=$IMAGE:nextjs
    - docker pull $IMAGE:nextjs || true
    - docker-compose -f docker-compose.yml build --no-cache
    - docker push $IMAGE:nextjs

deploy:
  stage: deploy
  script:
    - chmod +x ./deploy.sh
    - export NEXTJS_IMAGE=$IMAGE:nextjs
    - chmod +x ./scripts/deploy.sh
    - scp -r ./.env ./.dockerignore ./* $SSH_USER@$SSH_SERVER:~/app/website
    - bash ./scripts/deploy.sh