version: "3.8"

services:
  nextjs:
    image: "nextjs"
    container_name: nextjs
    ports:
      - "3001:3001"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
  nginx:
    image: "nginx"
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80