version: "3.8"

services:
  nextjs:
    image: registry.gitlab.com/pote.dev/website:nextjs
    container_name: nextjs
    ports:
      - ${APP_PORT}:${APP_PORT}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=dev.pote.dev
      - VIRTUAL_PORT=5000
      - APP_PORT=${APP_PORT}
      - LETSENCRYPT_HOST=dev.pote.dev
      - LETSENCRYPT_EMAIL=quentin@pote.dev
    restart: always

networks:
  default:
    external:
      name: nginx-proxy