version: "3.8"

services:
  nextjs:
    image: ${NEXTJS_IMAGE}
    container_name: website-nextjs
    ports:
      - ${APP_PORT}:${APP_PORT}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_NETWORK=${VIRTUAL_NETWORK}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - APP_PORT=${APP_PORT}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

networks:
  default:
    external:
      name: ${VIRTUAL_NETWORK}