echo NEXTJS_IMAGE=$IMAGE:nextjs  >> .env
echo APP_PORT=$APP_PORT  >> .env
echo VIRTUAL_HOST=$VIRTUAL_HOST >> .env
echo VIRTUAL_NETWORK=$VIRTUAL_NETWORK >> .env
echo VIRTUAL_PORT=$APP_PORT >> .env
echo LETSENCRYPT_HOST=$LETSENCRYPT_HOST >> .env
echo LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL >> .env
echo API_URL=$API_URL >> .env