
#API
echo API_BASE_URL=$API_BASE_URL >> .env

echo NEXTJS_IMAGE=$IMAGE:nextjs  >> .env

echo APP_PORT=$APP_PORT  >> .env

#NGINX
echo VIRTUAL_HOST=$VIRTUAL_HOST >> .env
echo VIRTUAL_NETWORK=$VIRTUAL_NETWORK >> .env
echo VIRTUAL_PORT=$APP_PORT >> .env
echo LETSENCRYPT_HOST=$LETSENCRYPT_HOST >> .env
echo LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL >> .env

